In [1]:
#Numpy


In [2]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np


In [2]:
# Creating Array

In [3]:
sample_array=np.array([1,2,3,4])

In [4]:
sample_array

array([1, 2, 3, 4])

In [5]:
#2d array(a maatrix)with 2 rows and 2 columns


In [8]:
sample_array_2=np.array([[1,2],[3,4]])

In [9]:
sample_array_2

array([[1, 2],
       [3, 4]])

In [10]:
sw=np.array([[1,2,3,4],[5,6,7,8]])

In [11]:
sw

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
#3d Tensor (2 matrices,each with 2 rows and 2 columns)

In [13]:
sample_tensor_3=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [14]:
sample_tensor_3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [15]:
example=np.array([[[3,42],[3,44]],[[45,6],[47,48]]])

In [16]:
example

array([[[ 3, 42],
        [ 3, 44]],

       [[45,  6],
        [47, 48]]])

In [18]:
#dimension

In [19]:
# if array is 0 dimension is called scalar
# if array is 1 dimension is called Vector(1-d(vector)[1,2,3,4])
# 2-d array(matrix)  (rows,columns)
#3-d Array(tensor)(page,rows,column)

In [20]:
#Array Properties

In [21]:
sample_array=np.array([[1,2,3],[4,5,6]])

In [22]:
sample_array

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
#shape

In [24]:
sample_array.shape

(2, 3)

In [26]:
#dimension


In [28]:
sample_array.ndim


2

In [31]:
#size

In [32]:
sample_array.size

6

In [34]:
sample_array.dtype

dtype('int64')

In [36]:
sa=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [38]:
sa.shape

(2, 2, 2)

In [39]:
sa.size

8

In [40]:
sa.ndim

3

In [41]:
sa.dtype

dtype('int64')

In [42]:
# special array

In [43]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [44]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [45]:
np.ones((100,100))

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]], shape=(100, 100))

In [47]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [49]:
np.arange(1,50,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [50]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [52]:
np.linspace(1,10,2)

array([ 1., 10.])

In [53]:
# indexing & slicing

In [54]:
Sample_array=np.array([10,20,30,40])

In [55]:
Sample_array

array([10, 20, 30, 40])

In [56]:
Sample_array[0]


np.int64(10)

In [57]:
Sample_array[2]

np.int64(30)

In [58]:
Sample_array[-1]

np.int64(40)

In [59]:
#slicing

In [60]:
sample_array[1:3]

array([[4, 5, 6]])

In [61]:
#array operations

In [62]:
a=np.array([1,2,3])

In [64]:
b=np.array([4,5,6])

In [69]:
a+b

array([ 8, 10, 12])

In [70]:
a-b

array([0, 0, 0])

In [71]:
a+b

array([ 8, 10, 12])

In [72]:
a*b

array([16, 25, 36])

In [79]:
s=np.array([1,2,3])

In [80]:
w=np.array([6,7,8])

In [81]:
s+w

array([ 7,  9, 11])

In [82]:
s-w

array([-5, -5, -5])

In [83]:
s*w

array([ 6, 14, 24])

In [84]:
s/w

array([0.16666667, 0.28571429, 0.375     ])

In [85]:
#Mathematical Functions

In [86]:
sample_array=np.array([1,4,9])

In [87]:
sample_array

array([1, 4, 9])

In [88]:
np.sqrt(sample_array)

array([1., 2., 3.])

In [90]:
pw=np.array([4,5,6,7])

In [92]:
pw

array([4, 5, 6, 7])

In [93]:
np.sqrt(pw)

array([2.        , 2.23606798, 2.44948974, 2.64575131])

In [94]:
np.exp(sample_array)

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03])

In [95]:
np.log(sample_array)

array([0.        , 1.38629436, 2.19722458])

In [96]:
#Statistical Functions

In [97]:
sample_array=np.array([1,2,3,4,5])

In [98]:
sample_array


array([1, 2, 3, 4, 5])

In [99]:
np.mean(sample_array)

np.float64(3.0)

In [100]:
np.median(sample_array)

np.float64(3.0)

In [103]:
np.std(sample_array)

np.float64(1.4142135623730951)

In [105]:
np.max(sample_array)

np.int64(5)

In [107]:
#  reshaping  array

In [108]:
sample_array=np.arange(0,6)

In [109]:
sample_array

array([0, 1, 2, 3, 4, 5])

In [112]:
sample_array.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [113]:
# Flattening

In [114]:
sample_array=np.array([[1,2],[3,4]])

In [115]:
sample_array

array([[1, 2],
       [3, 4]])

In [116]:
sample_array.flatten()

array([1, 2, 3, 4])

In [117]:
sample_array=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [119]:
sample_array.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [120]:
# Joining Arrays

In [125]:
a=np.array([1,2,3])

In [126]:
a

array([1, 2, 3])

In [128]:
b=np.array([4,5,6])

In [129]:
b

array([4, 5, 6])

In [130]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

In [132]:
#split array

In [136]:
sample_array=np.array([1,2,3,4,5])

In [137]:
sample_array

array([1, 2, 3, 4, 5])

In [138]:
np.array_split(sample_array,2)

[array([1, 2, 3]), array([4, 5])]

In [140]:
# Random module

In [141]:
np.random.rand(3)

array([0.61831246, 0.65896524, 0.15228965])

In [143]:
np.random.randint(1,10,5)

array([7, 3, 3, 6, 7], dtype=int32)

In [144]:
# Axis concept

In [145]:
sample_array=np.array([[1,2],[3,4]])

In [146]:
sample_array

array([[1, 2],
       [3, 4]])

In [148]:
np.sum(sample_array,axis=0)

array([4, 6])

In [149]:
np.sum(sample_array,axis=1)

array([3, 7])

In [150]:
#Nan & Missing values

In [151]:
sample_array=np.array([1,np.nan,3])

In [152]:
sample_array

array([ 1., nan,  3.])

In [153]:
np.isnan(sample_array)

array([False,  True, False])

In [154]:
# create a two numpy arrays and perform element vise multiplication and modules operations

In [155]:
a=np.array([1,2,3,4,5])

In [156]:
b=np.array([6,7,8,9,10])

In [157]:
a*b

array([ 6, 14, 24, 36, 50])

In [158]:
a%b

array([1, 2, 3, 4, 5])